### ISSUE TITLE
Add video/gif at the top of the readme

### ISSUE THREAD

**Issue by Murderlon** [indaco/goaster#1]
Hi, this looks really cool and the templ ecosystem needs more things like this!

I think this project would do a lot better however if there was a gif or video at the top of the readme showing the default styles and the animation.

**Comment by indaco** [comment]
Thanks @Murderlon 

Will do, for sure!

**Comment by indaco** [comment]
demo video added - [2796c5a](https://github.com/indaco/goaster/commit/2796c5a6b990a5cea22938aea41140afb117dcb7)
